import net.minecraft.src.*;
import java.io.File;
import java.lang.reflect.Field;
import java.util.Random;

public class DebugSandstone {
    public static void main(String[] args) {
        long seed = -100L;
        ISaveHandler saveHandler = new SaveHandler(new File("."), "DebugWorld", false);
        WorldProvider worldProvider = WorldProvider.getProviderForDimension(0);
        World world = new World(saveHandler, "DebugWorld", worldProvider, seed);

        // We need to subclass to access the protected/private logic easily or just
        // replicate it
        // Simulating the loop logic using the extracted noise values is safest.

        ChunkProviderGenerate provider = new ChunkProviderGenerate(world, seed);

        try {
            provider.provideChunk(0, 0); // Populate arrays

            Field sandNoiseF = ChunkProviderGenerate.class.getDeclaredField("sandNoise");
            Field stoneNoiseF = ChunkProviderGenerate.class.getDeclaredField("stoneNoise");
            sandNoiseF.setAccessible(true);
            stoneNoiseF.setAccessible(true);

            double[] sandNoise = (double[]) sandNoiseF.get(provider);
            double[] stoneNoise = (double[]) stoneNoiseF.get(provider);

            // Replicate Col 0,0 logic
            Random rand = new Random((long) 0 * 341873128712L + (long) 0 * 132897987541L);
            int idx = 0;

            double sandRnd = rand.nextDouble();
            boolean genSand = sandNoise[idx] + sandRnd * 0.2 > 0.0;
            double gravelRnd = rand.nextDouble(); // consume
            double stoneRnd = rand.nextDouble();
            int stoneDepth = (int) (stoneNoise[idx] / 3.0 + 3.0 + stoneRnd * 0.25);

            System.out.println("Java Col(0,0): Sand=" + genSand + " Depth=" + stoneDepth);

            int remainingDepth = -1;
            int fillerBlock = 3; // Dirt

            // Replicate the Y loop
            // We need the ACTUAL block IDs generated by Java.
            // We can get the chunk and inspect it.
            Chunk chunk = provider.provideChunk(0, 0);

            System.out.println("Checking for Sandstone (ID 24) in Col 0,0:");
            boolean found = false;
            for (int y = 127; y >= 0; y--) {
                int id = chunk.getBlockID(0, y, 0);
                if (id == 24) {
                    System.out.println("  FOUND Sandstone at y=" + y);
                    found = true;
                }
            }
            if (!found)
                System.out.println("  NO Sandstone found.");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}